# Utiliza una imagen de Node.js como base
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Compila la aplicación ReactJS
RUN npm run build

# Expone el puerto 3000 para acceder a la aplicación desde el host
EXPOSE 4173

# Define el comando para ejecutar el servidor de desarrollo de Vite
CMD ["npm", "run", "start"]
